sudo: required
dist: trusty

os: linux

language: c

cache:
  directories:
  - download-cache

compiler:
  - gcc
  - clang

env:
  global:
    - LUAJIT_PREFIX=/opt/luajit21
    - LUAJIT_LIB=$LUAJIT_PREFIX/lib
    - LD_LIBRARY_PATH=$LUAJIT_LIB:$LD_LIBRARY_PATH
    - LUAJIT_INC=$LUAJIT_PREFIX/include/luajit-2.1
    - LUA_INCLUDE_DIR=$LUAJIT_INC
    - LUA_CMODULE_DIR=/lib
    - JOBS=3
    - NGX_BUILD_JOBS=$JOBS
  matrix:
    - NGINX_VERSION=1.9.15

services:
 - redis-server

before_install:
  - script/before_install

install:
  - script/build_environment
  - script/build_luajit

script:
  - script/test
