#!/bin/bash

cd ~/work/nginx

git clone -b v2.1-agentzh https://github.com/openresty/luajit2.git || true

cd luajit2
make -j$JOBS PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS='-DLUA_USE_APICHECK -DLUA_USE_ASSERT' > build.log 2>&1 || (cat build.log && exit 1)
sudo make install PREFIX=$LUAJIT_PREFIX > build.log 2>&1 || (cat build.log && exit 1)
